name: get_uvinstall

on: 
  schedule:
    - cron: "0 8 * * *"

jobs:
  get_uvinstall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get uvscipt
        run: curl -L -O https://astral.sh/uv/install.ps1
      - name: Commit
        run: |
          git config --global user.email gjkevin2@163.com
          git config --global user.name gjkevin
          git add .
          git commit -m"action:`date`"
          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}